service: serverless-birds-v2

plugins:
  - serverless-iam-roles-per-function
provider:
  name: aws
  runtime: python3.8
  region: eu-central-1
  lambdaHashingVersion: 20201221

functions:
  createBird:
    handler: functions/create_bird.lambda_handler
    events:
      - http:
          path: /birds
          method: post
  getBird:
    handler: functions/get_bird.lambda_handler
    events:
      - http:
          path: /birds/{id}
          method: get
